### ISSUE TITLE
Possible to use Gruntfile's compass config for Sass?

### ISSUE THREAD

**Issue by Melindrea** [peterkeating/grunt-csscss#1]
I still haven't decided on whether I am preferring to run CSSCSS on the uncompiled files or on the compiled CSS, but I don't use a config.rb file but rather the compass options in my Gruntfile.

Can the task handle it, and if so, how?

**Comment by peterkeating** [comment]
Hey Marie, 

Unfortunately it can't use Compass options, due to CSSCSS not accepting Compass arguments. As you pointed out the best alternative is to use your Compass task to convert Sass to CSS, and then run the CSSCSS task against the CSS file that was created.

**Comment by Melindrea** [comment]
Alright, thanks. I'll try the task out after work and see if I have any other comments. Awesomely done, btw, much appreciated task!

**Comment by peterkeating** [comment]
Thanks Marie, any feedback would be great! :)
