### ISSUE TITLE
Support sass globbing

### ISSUE THREAD

**Issue by Anahkiasen** [peterkeating/grunt-csscss#13]
The linter currently fails on glob style imports in Sass such as those:

``` scss
@import "helpers/*";
```

Would be great if those were supported

```
public/app/sass/styles.scss:2: File to import not found or unreadable: helpers/*. (Sass::SyntaxError)
```

**Comment by peterkeating** [comment]
Think this is an issue for the CSSCSS Ruby gem that this Grunt plugin uses.

https://github.com/zmoazeni/csscss

**Comment by Anahkiasen** [comment]
Yup
