### ISSUE TITLE
Json output

### ISSUE THREAD

**Issue by aquelito** [peterkeating/grunt-csscss#14]
Hello,

The generated code does not seem valid ?

Exemple for an empty file :

``` json
{
    "dist/css/screen.css": [
}
```

**Comment by peterkeating** [comment]
Hello @aquelito 

Firstly, apologies for the slack reply!

I've tried to replicate the behavior you're seeing but I'm not having much luck. I've created a [separate branch](https://github.com/peterkeating/grunt-csscss/tree/issue/14) where I've updated the csscss:outputToFile task in the `gruntfile.js` file to perform the CSSCSS on a CSS file that contains no duplicates. 

The output (in `ignore/output.json` once you run the `csscss:outputToFile` grunt task) I'm seeing looks to be valid JSON, maybe I'm missing something though that isn't quite replicating what you're seeing?

```
{
     "test/example/no-duplicates.css": []
}
```
