### ISSUE TITLE
Cannot find Duplicate Selectors

### ISSUE THREAD

**Issue by shmdhussain** [peterkeating/grunt-csscss#15]
Not able to find duplicate selectors like .header{color:red} and .header{color:green}. Only find properties that are shared between multiple selectors. Is there a way or am i doing something wrong?

**Comment by peterkeating** [comment]
I don't think CSSCSS looks for duplicates like that, as you mentioned it only highlights common properties between multiple selectors. I've seen recently someone open a [similar issue](https://github.com/zmoazeni/csscss/issues/92) in the CSSCSS project. Maybe using a [CSS linting tool](https://github.com/CSSLint/csslint/) to find duplicates similar to your example would be more appropriate.
