### ISSUE TITLE
Aborting if there are duplicate styles

### ISSUE THREAD

**Issue by Melindrea** [peterkeating/grunt-csscss#2]
I think that's the first thing that's coming to my mind. I'd be wanting to use CSSCSS in automated testing, setting a threshold for what I'd find acceptable, and then have it abort if there are duplicate styles. 

I can also, obviously, see why people might not want that, but what do you think about an option for "break on duplicate"?

**Comment by peterkeating** [comment]
Excellent suggestion :) Will have a play around with implementing this option.

**Comment by peterkeating** [comment]
Added `featureWhenDuplicates` option, which when set to `true` will fail the grunt task if CSSCSS reports any rules sets that contain duplicates. Have pushed this into version 0.3.0, which I have just published to NPM, so if you update the grunt-csscss package, you should be able to use that option.
