### ISSUE TITLE
Aborted due to warnings (a wee bit too sensitive... =)

### ISSUE THREAD

**Issue by Melindrea** [peterkeating/grunt-csscss#3]
Thanks again for fixing #2, and I just tested it out, with the following output:

```
Running "csscss:dist" (csscss) task
.tmp/style.css
[]

Warning: Failed due to matches found by CSSCSS. Use --force to continue.

Aborted due to warnings.
```

**Comment by peterkeating** [comment]
Interesting, wonder why CSSCSS is outputting an empty array. What are the options you're passing to CSSCSS? Also, out of curiosity what is the CSS in .tmp/style.css?

**Comment by Melindrea** [comment]
Options:

```
csscss: {
        options: {
            verbose: true,
            outputJson: true,
            compass: true,
            failWhenDuplicates: true
        },
        dist: {
            src: ['.tmp/style.css']
        }
    },
```

CSS: https://gist.github.com/Melindrea/5402865#file-style-css (after I realised how big the file actually is -- 1004 lines).

I'm assuming the reason it outputted an empty array is because there are no duplicates. It's a quite basic stylesheet at the moment, mainly Normalizer followed by Typeplate and a few minor adjustments.

**Comment by peterkeating** [comment]
Ah the reason is because your output is JSON, that makes perfect sense. Will get this sorted for you as soon as I can :) 

Thanks a bunch!

**Comment by Melindrea** [comment]
I like the cleanliness of JSON =)

**Comment by peterkeating** [comment]
All sorted, thanks Marie, your feedback is very much appreciated :)

Keep opening issues if you find anything else or can think of anything else that would be useful.
