### ISSUE TITLE
Theorising on how to get this task to work with having compass config in a Gruntfile.js

### ISSUE THREAD

**Issue by Melindrea** [peterkeating/grunt-csscss#4]
For starters, this is more meant as a place where discussion can start, not a "fix this!", and depending on your thoughts I might be able to help with writing it. I've been needing to figure out how to write Grunt tasks a while now.

Okay, so the usecase I have is that I use the grunt task [Grunt-contrib-compass](https://github.com/gruntjs/grunt-contrib-compass) and store all of my config options in my Gruntfile.js, which means that using the compass config option is not a, ehm, option =)

Would it be a possibility, you think, to as part of the task create a temporary file, using data from the Compass task config, and use that when running CSSCSS through Grunt?

**Comment by peterkeating** [comment]
Hey Marie,

That would definitely be possible as that's exactly what the grunt-contrib-compass task does. You can see it here in [this JavaScript file](https://github.com/gruntjs/grunt-contrib-compass/blob/master/tasks/lib/compass.js) that it is creating a temporarily config.

Whether we want this in the grunt-csscss task I am still unsure of, my worry is that it would be adding too much, but I can definitely see the benefit because if you're using Compass & Grunt the chances are you're probably not using a config.rb, instead specifying the options via the Compass grunt task instead.

**Comment by Melindrea** [comment]
Yeah, I can see that worry, it is a lot better to have five tools that are awesome at five different things than a single tool that half-asses said five different things.

There's discussions [here](https://github.com/zmoazeni/csscss/issues/54) on the possibility to specify a file that holds the configs, which means that anything to be done with the task should probably wait until they've decided on how to implement it there.

**Comment by peterkeating** [comment]
Yea I have been keeping an eye on that discussion :)

Shall keep this issue open, wait to see what Zach does with the `--require` flag, then discuss if we still want to implement creating a temporary config.rb file.

**Comment by Melindrea** [comment]
Sounds like a plan! I'm still trying to figure out if I prefer running this on the .scss file(s) or on the compile .css file, since both of them have merits. I am just far too much of a programmer to _not_ want my options open =)

**Comment by Melindrea** [comment]
Alright, I've been doing a bit of testing now. It seems that yes, we'd still need to have some way to generate a temporary config.rb, if one wants to be able to use the grunt-contrib-compass task with the bells and whistles of yeoman... 

I got errors until I required the gem, added additional import paths, sett the images dir and the fonts dir in my own config file.

**Comment by zmoazeni** [comment]
@peterkeating @Melindrea I just implemented the `--require` flag. That will go out in the next release (likely 1.3.0)

**Comment by peterkeating** [comment]
I have updated the grunt task to include all the new features in 1.3.1. 

If you could take a look Marie that would be great. Still unsure about getting the grunt task to create a temporary config file.

**Comment by Melindrea** [comment]
Looks good! There is a spelling error in the error message that compassConfig is deprecated, however.

**Comment by peterkeating** [comment]
Good spot :)
