### ISSUE TITLE
Run csscss with `bundle exec`

### ISSUE THREAD

**Issue by robwierzbowski** [peterkeating/grunt-csscss#6]
It would be nice to be able to run this task with `bundle exec` like [grunt-contrib-compass](https://github.com/gruntjs/grunt-contrib-compass#bundleexec) and [grunt-jekyll](https://github.com/dannygarcia/grunt-jekyll).

**Comment by peterkeating** [comment]
Will look into this, shouldn't be too difficult.

**Comment by peterkeating** [comment]
Think this is sorted :) Would be really helpful if you could double check for me.

**Comment by robwierzbowski** [comment]
Double checked and working well. Thanks for the quick addition.

**Comment by peterkeating** [comment]
Thanks for the suggestion :) Will work on your other suggestion soon and hopefully have that implemented by tonight :)

**Comment by robwierzbowski** [comment]
Sweet!
