### ISSUE TITLE
Save output to a file

### ISSUE THREAD

**Issue by paazmaya** [peterkeating/grunt-csscss#8]
Allow to use Grunt task `files` property for setting the destination file where the output will be directed instead of stdout in case it is defined.

**Comment by paazmaya** [comment]
Example usage

``` js
csscss: {
      options: {
        outputJson: true
      },
      dist: {
        'csscss.json': ['css/*.css']
      }
    }
```

**Comment by peterkeating** [comment]
Nice idea :) Will take a look at this for you.

**Comment by paazmaya** [comment]
Thank you!

Before that, I can just run the command by hand with `> csscss.json`

**Comment by peterkeating** [comment]
Played around with your idea last night, Managed to get something together, however my concern is when using the glob feature to process multiple files and outputting JSON, the JSON is not valid. Below is an example.

```
[]
[]
[{"selectors":[".rule-b",".rule-c"],"count":2,"declarations":["border: 1px solid #000","margin: 0"]}]
```

Any thoughts?

**Comment by paazmaya** [comment]
Are you referring to this? http://gruntjs.com/configuring-tasks#globbing-patterns 

I was thinking something like

``` js
csscss: {
      options: {
        outputJson: true
      },
      dist: {
        'csscss.json': ['css/*.css'],
        'csscss_other.json': ['other/*.css']
      }
    }
```

Which would create single file for the given set of source files.

But if you mean that single src that contains for example \* in this case, would result that invalid json, then each of the resulting arrays should be keys with src filename and wrapped in a object to make it valid.

Taken the example from your comment, the resulting output would be something like this:

``` js
{
  "file1.css": [],
  "other.css": [],
  "some.css": [{"selectors":[".rule-b",".rule-c"],"count":2,"declarations":["border: 1px solid #000","margin: 0"]}]
}
```

**Comment by peterkeating** [comment]
That's exactly what I mean with regards to a single src that contains *. 

I was also thinking the resulting output would look like what you've specified.

**Comment by paazmaya** [comment]
But are you getting those array per f.src ?
If yes, then just save them to a internal data storage and once the given destination is handled, save that data in it.
I am sure you already tried.... so can you push the version to another branch?

**Comment by peterkeating** [comment]
Looks like I have fallen into a trap with this task as point out in [this article](http://dontkry.com/posts/code/2013-04-24-use-this-files.html). I am using `this.data` but I should be using `this.files`. Now I could just add a `dest` property that can be accessed via `this.data.dest`, or I could do it the proper way and refactor the task to use `this.files`.

**Comment by paazmaya** [comment]
:sake:

**Comment by peterkeating** [comment]
Apologies :( Will get it sorted today / this evening!

**Comment by peterkeating** [comment]
Pushed the branch up for you. If you could give it a test that would be great, let me know how it goes and if there are any issues.

**Comment by paazmaya** [comment]
Thank you very much, I will look at it soon. Had a busy and long weekend...

**Comment by paazmaya** [comment]
With the example in https://github.com/peterkeating/grunt-csscss/issues/8#issuecomment-22162293
I get `File: [no files]` once running `grunt csscss -v`.

**Comment by peterkeating** [comment]
What happens if you run `grunt csscss -v` on the grunt file that is included in this repository?

**Comment by paazmaya** [comment]
That seems to work, and even if my config looks like the `outputTofile` task, must be in my end...

**Comment by paazmaya** [comment]
I seem to be missing the `files` wrapping object in all of the examples above and since I copied my configuration from those, it had the same mistake.

Looks great!
:shipit:

**Comment by peterkeating** [comment]
Ah okay! Brilliant! Will push this (`v0.6.0`) to NPM over the weekend :) 

Thanks for the suggestion, really appreciate it.
